research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    consider the current year and 2024.
  expected_output: >
    A list with 5 bullet points of the most relevant information about {topic}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst

blogging_task:
  description: >
    Write a blog post about {topic}.
    Ensure the content is engaging and informative.
  expected_output: >
    A blog post with a title and content formatted in markdown.
  agent: blog_writer
